//
//  AnyPropertyPublisher.swift
//  Publishable
//
//  Created by Kamil Strzelecki on 17/01/2025.
//  Copyright © 2025 Kamil Strzelecki. All rights reserved.
//

import Combine

/// An object that exposes `Combine` publishers for  ``willChange`` and ``didChange`` events.
///
/// Subclasses of this class are generated by the ``Publishable()`` macro,
/// and provide publishers for all mutable instance properties of the type the macro is applied to.
///
open class AnyPropertyPublisher<Object: AnyObject> {
    private unowned let object: Object

    @_documentation(visibility: private)
    public init(object: Object) {
        self.object = object
    }
}

extension PassthroughSubject: @unchecked @retroactive Sendable {}

// swiftlint:disable identifier_name

extension AnyPropertyPublisher {

    public func _storedPropertyPublisher<T>(
        _ subject: PassthroughSubject<T, Never>,
        for keyPath: KeyPath<Object, T>
    ) -> some Publisher<T, Never> {
        subject
            .prepend(object[keyPath: keyPath])
    }

    public func _storedPropertyPublisher<T: Equatable>(
        _ subject: PassthroughSubject<T, Never>,
        for keyPath: KeyPath<Object, T>
    ) -> some Publisher<T, Never> {
        subject
            .prepend(object[keyPath: keyPath])
            .removeDuplicates()
    }
}

// swiftlint:enable identifier_name
